/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppConfig: typeof import('./src/components/AppConfig.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    AppTopbar: typeof import('./src/components/AppTopbar.vue')['default']
    Button: typeof import('primevue/button')['default']
    Empty: typeof import('./src/components/Empty.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
